# -*- coding: utf-8 -*-
"""Introduction to NN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17V-CezG_tO0170uX07stSUC6PwgjyUF2
"""

from tensorflow.keras.datasets import mnist, cifar10

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

#load MNIST


(X_train_mist, y_train_mist), (X_test_mist, y_test_mist) = mnist.load_data()

print(X_test_mist.shape)
print(X_train_mist.shape)

#load CIFAR-10

(X_train_cifar, y_train_cifar), (X_test_cifar, y_test_cifar) = cifar10.load_data()

print(X_test_cifar.shape)
print(X_train_cifar.shape)

# define a basic dense layer

layer = tf.keras.layers.Dense(units=10, activation='relu')
print(f"TensorFlow Layer : {layer}")

# a basic dense layer

layer = nn.Linear(in_features=10, out_features=5)
print(f"PyTorch Layer : {layer}")

#visualize

plt.imshow(X_train_mist[0], cmap='gray')
plt.title(f"MNIST Label : {y_train_mist[0]}")
plt.show()

plt.imshow(X_train_cifar[0])
plt.title(f"CIFAR_10 Label : {y_train_cifar[0]}")

